
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int width = 21;
  public static final int height = 22;
  public static final int suma = 30;
  public static final int resta = 31;
  public static final int number_int = 37;
  public static final int url = 18;
  public static final int html_c = 3;
  public static final int table_c = 10;
  public static final int html_a = 2;
  public static final int table_a = 9;
  public static final int body_c = 8;
  public static final int coma = 25;
  public static final int igual = 26;
  public static final int body_a = 7;
  public static final int bold_font = 23;
  public static final int head_c = 5;
  public static final int head_a = 4;
  public static final int border = 19;
  public static final int name = 20;
  public static final int email = 35;
  public static final int EOF = 0;
  public static final int punto_coma = 29;
  public static final int image_c = 15;
  public static final int comillas = 34;
  public static final int producto = 32;
  public static final int image_a = 14;
  public static final int error = 1;
  public static final int row_c = 12;
  public static final int row_a = 11;
  public static final int number_float = 38;
  public static final int webpage = 36;
  public static final int parentesis_c = 28;
  public static final int parentesis_a = 27;
  public static final int list_c = 17;
  public static final int list_a = 16;
  public static final int column = 13;
  public static final int titulo = 6;
  public static final int dato = 39;
  public static final int print = 24;
  public static final int division = 33;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "html_a",
  "html_c",
  "head_a",
  "head_c",
  "titulo",
  "body_a",
  "body_c",
  "table_a",
  "table_c",
  "row_a",
  "row_c",
  "column",
  "image_a",
  "image_c",
  "list_a",
  "list_c",
  "url",
  "border",
  "name",
  "width",
  "height",
  "bold_font",
  "print",
  "coma",
  "igual",
  "parentesis_a",
  "parentesis_c",
  "punto_coma",
  "suma",
  "resta",
  "producto",
  "division",
  "comillas",
  "email",
  "webpage",
  "number_int",
  "number_float",
  "dato"
  };
}

